### ISSUE TITLE
Move processing of individual messages to a separate PHP process

### ISSUE THREAD

**Issue by mpdude** [bernardphp/bernard#167]
We're considering replacing a POC queue-processing application with Bernard. One feature the current solution has is to move processing of the individual messages to a separate PHP process. The main "consumer" process waits for this child to finish before it continues.

The main reasons for doing so were that a) once the "worker" exits all resources will be freed (no problems with GC/memory leaks) and b) every worker starts in a "clean" process.

Regarding b), you might for example run into problems when workers require database connections that might be shut down after some time. Starting new processes avoids having to deal with this kind of errors.

Would you guys be open for PRs that try to implement this feature? Has it been tried before and rejected?

**Comment by henrikbjorn** [comment]
In the early days we used https://github.com/kriswallsmith/spork to fork out the processing for every single message. The problem with this is to make sure, you catch errors, wait for the process to finish and that they wont just "die".

Also it is slower because you are waiting for resources when forking (rememeber its a whole new process and not just a new thread).

Fell free to open a PR with the feature, if it is as a drop in, with events or a custom consumer.
