### ISSUE TITLE
Return false from consumer

### ISSUE THREAD

**Issue by davidsteinsland** [bernardphp/bernard#191]
As far as I can see, there's only one option to report that the consumer failed, and that is to throw an exception from within the worker? This will create the `rejected` event, but shouldn't there be a more simpler option, such as just return `false`?

Documentation can probably be improved on the error handling subject. When a job fails, it's very useful to be alerted of this so that the right backup procedures may be called.

**Comment by henrikbjorn** [comment]
The thing about failing a message by returning false, is that no context is provided at all other than "fail". By forcing a exception you provide some context also we dont have to require receivers to return `true` everywhere.

**Comment by davidsteinsland** [comment]
Hm, yes, that sounds reasonable. But I'm not quite sure if I like that the Consumer actually swallows the exception. 

I have a setup that involves using `supervisord` (so crashed workers due to exceptions being thrown is not a problem), *and* I have an exception handler that notifies services such as Airbreak/Rollbar. But when the consumer catches all exceptions, these will never reach my error handlers.

I have thought that maybe I should write my own Middleware that reports exceptions, but it seems that I would have to write one factory, and then the middleware itself..? Seems a bit overkill ...

**Comment by henrikbjorn** [comment]
The reason the consume swallows all exceptions is that it is a long running process, and we dont want it to die because of business logic throwing an exception.

You are correct you need to implement your own middleware such as https://github.com/bernardphp/bernard/blob/0.12.2/src/Bernard/Middleware/LoggerMiddleware.php or just use that one with Monolog (and have monolog log exceptions to Airbrake/Rollbar) - In the master branch this is replaced by events, such as those you find for Symfony's request cycle or console exception event.

If you have ideas for improvements of the consumer i am very happy to discuss those.

**Comment by davidsteinsland** [comment]
:+1: 

What are the current plans for drivers? I see there's no driver for `Gearman` yet, and I thought perhaps I'd write one. Do you want drivers as a PR or are you fine with separate repos (e.g. under my user)?

**Comment by henrikbjorn** [comment]
Feel free to create a driver for Gearman, it is impossible for me to implement them all, and most of the others are by the Community. You decide if you want it under your own repo or as a PR. However, if its a PR the coding style we use and tests are required for it to be merged.
