### ISSUE TITLE
Messages are not marked as acknowledged

### ISSUE THREAD

**Issue by robinvdvleuten** [bernardphp/bernard#198]
Somehow my messages are not marked as acknowledged in RabbitMQ and it seems not to work for other drivers as well. When I create a new default message like this;

```php
$this->get('bernard.producer')->produce(new DefaultMessage('SubmitMessage', [
    'id' => $entity->getId()
]));
```

It goes correctly to a queue called `submit-message`. So I run a consumer like this;

```bash
app/console bernard:consume submit-message --no-debug
```

And it processes the message correctly. But it's never marked as acknowledged because of [this line](https://github.com/bernardphp/bernard/blob/master/src/Queue/RoundRobinQueue.php#L188). The `$queue` variable contains the string `SubmitMessage` but the queue's key is `submit-message`, so this isset will always fail. Am I doing something wrong or is this a bug?

**Comment by henrikbjorn** [comment]
@robinvdvleuten This is a bug. The RoundRobinQueue needs to "save" which queue the envelopes comes from and use that map to acknowledge it.

**Comment by henrikbjorn** [comment]
A quick fix would be to use the function that normalizes Envelope names into queue names.

**Comment by henrikbjorn** [comment]
@elazar can you look at this?

**Comment by elazar** [comment]
> A quick fix would be to use the function that normalizes Envelope names into queue names.

@henrikbjorn There's an existing function that does this? Can you point me to it?

**Comment by henrikbjorn** [comment]
@elazar https://github.com/bernardphp/bernard/blob/master/src/Util.php#L15

But i would rather fix it in another way.

**Comment by elazar** [comment]
@henrikbjorn I'm open to suggestions. I'd rather see what's there fixed than see it pulled.

**Comment by henrikbjorn** [comment]
@elazar i think that when you get the envelope, you need to save its object hash, and what queue it came from, so when its acknowledge you are certain on the queue name, PersistentQueue does something similiar for Receipts

**Comment by elazar** [comment]
@robinvdvleuten Are you specifying multiple queues that aren't shown in your example command here? [These tests](https://github.com/bernardphp/bernard/blob/6d3f84e73ce89ce671c98dcb1b9d02bc08850025/tests/Command/ConsumeCommandTest.php#L18-L60) should cover both cases for [this code](https://github.com/bernardphp/bernard/blob/6d3f84e73ce89ce671c98dcb1b9d02bc08850025/src/Command/ConsumeCommand.php#L62-L66). If you're inadvertently triggering the round robin case, there's another bug here that should be fixed.

**Comment by elazar** [comment]
@henrikbjorn I don't follow you.

`PersistentQueue` is only ever dealing with a single queue, and the name for it is passed to its constructor when `PersistentQueueFactory` creates it. So, it has a definitive means to identify that queue.

`RoundRobinQueue` is dealing with multiple queue instances, must be able to identify them individually, and has only has their literal names (as passed in from command line and [returned by `__toString()`](https://github.com/bernardphp/bernard/blob/6d3f84e73ce89ce671c98dcb1b9d02bc08850025/src/Queue/RoundRobinQueue.php#L174)) and the equivalent return values of `Util::guessQueue()` (which `Producer` [also uses](https://github.com/bernardphp/bernard/blob/6d3f84e73ce89ce671c98dcb1b9d02bc08850025/src/Producer.php#L32) in the first use case cited by @robinvdvleuten) in order to identify them.

I'm happy to fix this, and obviously want to do so correctly, but if your preference is that I not use `Util::guessQueue()`, I'm not sure how you expect me to reliably identify any given queue.

**Comment by henrikbjorn** [comment]
@elazar if you look at PersistentQueue, then it saves object hashes for Envelope's when get are dequeued(). If you do the same and save a objecthash -> queue name, then you can use that to lookup the correct queue?

**Comment by robinvdvleuten** [comment]
@elazar I am using a single queue in my SF2 application.

**Comment by elazar** [comment]
@henrikbjorn I've submitted #200 to attempt to fix this. I believe it's consistent with how you wanted me to approach fixing this, but let me know if you see any issues.

@robinvdvleuten Any chance you could test with the changes from #200 to confirm that they address your issue?

**Comment by elazar** [comment]
I've also filed #201 for what is apparently a separate issue with `ConsumeCommand` always using `RoundRobinQueue` regardless of how many queues are specified when it's run. I'll try to code a fix for this later on today.
